sudo: false

language: node_js
node_js:
- '8'
- '9'
- '10'

cache:
  directories:
    - node_modules

before_install: if [[ `npm -v` != 6* ]]; then npm i -g npm@6; fi

script:
  - npm test -- --coverage
  - npm run build

after_script:
  - COVERALLS_REPO_TOKEN=$coveralls_repo_token npm run coveralls

notifications:
  slack: leduong:8FHnajypcfOykiQS6Hn6QBB5
